---
- name: Update packages list
  become: true
  apt:
    update_cache: yes

- name: Install apt-transport-https and curl
  become: true
  apt:
    pkg:
      - apt-transport-https
      - curl

- name: Add Kubernetes apt list
  become: true
  shell:
    cmd: |
      curl -s https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
      cat <<EOF | sudo tee /etc/apt/sources.list.d/kubernetes.list
      deb https://apt.kubernetes.io/ kubernetes-xenial main
      EOF

- name: Update apt lists
  become: true
  apt:
    update_cache: yes

- name: Install kubelet, kubeadm and kubectl
  become: true
  apt:
    pkg:
      - kubelet
      - kubeadm
      - kubelet